INFO:    underlay of /etc/localtime required more than 50 (91) bind mounts
[ WARN:0@0.741] global loadsave.cpp:244 findDecoder imread_('../data/processed_data/20237838-809_eid-2_L_CC.png'): can't open/read file: check file path/integrity
[ WARN:0@0.743] global loadsave.cpp:244 findDecoder imread_('../data/processed_data/20237838-809_eid-2_L_MLO.png'): can't open/read file: check file path/integrity
[ WARN:0@0.743] global loadsave.cpp:244 findDecoder imread_('../data/processed_data/20237838-809_eid-2_R_CC.png'): can't open/read file: check file path/integrity
[ WARN:0@0.743] global loadsave.cpp:244 findDecoder imread_('../data/processed_data/20237838-809_eid-2_R_MLO.png'): can't open/read file: check file path/integrity
mogoce dela
ne res ja
getdata monaa
182
/d/hpc/home/ris002/joskogled/src     ../data/processed_data/20237838-809_eid-2_L_CC.png
Traceback (most recent call last):
  File "/d/hpc/home/ris002/joskogled/src/main.py", line 78, in <module>
    main()
  File "/d/hpc/home/ris002/joskogled/src/main.py", line 42, in main
    for batch_idx, (
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 678, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/d/hpc/home/ris002/joskogled/src/dataloader.py", line 49, in __getitem__
    print(l_cc_image.shape)
AttributeError: 'NoneType' object has no attribute 'shape'
